In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[5.8997e-11, 4.5584e-41, 5.8997e-11],
        [4.5584e-41,        nan, 3.0801e-41],
        [7.6194e+31, 1.5564e+28, 1.8484e+31],
        [1.8370e+25, 1.4603e-19, 2.7517e+12],
        [7.5338e+28, 3.0313e+32, 6.3828e+28]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2319, 0.7224, 0.3507],
        [0.3872, 0.2377, 0.3387],
        [0.7350, 0.5672, 0.9871],
        [0.5081, 0.0380, 0.8911],
        [0.1502, 0.0365, 0.9340]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1214,  1.1977, -0.8712],
        [ 0.5977, -1.6812, -0.7207],
        [-0.1202,  0.8661, -1.6275],
        [ 0.2601,  0.4442,  1.3383],
        [ 0.2522, -1.1503,  0.0521]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4724,  1.2413,  0.0133],
        [ 1.4904, -1.0449, -0.2327],
        [ 0.7342,  1.4633, -0.7687],
        [ 1.1636,  1.2029,  2.3293],
        [ 0.7244, -0.4248,  0.4349]])


In [9]:
print(torch.add(x, y))

tensor([[ 0.4724,  1.2413,  0.0133],
        [ 1.4904, -1.0449, -0.2327],
        [ 0.7342,  1.4633, -0.7687],
        [ 1.1636,  1.2029,  2.3293],
        [ 0.7244, -0.4248,  0.4349]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4724,  1.2413,  0.0133],
        [ 1.4904, -1.0449, -0.2327],
        [ 0.7342,  1.4633, -0.7687],
        [ 1.1636,  1.2029,  2.3293],
        [ 0.7244, -0.4248,  0.4349]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.4724,  1.2413,  0.0133],
        [ 1.4904, -1.0449, -0.2327],
        [ 0.7342,  1.4633, -0.7687],
        [ 1.1636,  1.2029,  2.3293],
        [ 0.7244, -0.4248,  0.4349]])


In [12]:
print(x[:, 1])

tensor([ 1.1977, -1.6812,  0.8661,  0.4442, -1.1503])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.2048])
-2.2047884464263916


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-1.2048], device='cuda:0')
tensor([-1.2048], dtype=torch.float64)
